### ISSUE TITLE
Convert it to kindle format

### ISSUE THREAD

**Issue by carvalhar** [itayperl/lsj-kindle#1]
Hi,

I found your project by searching about a greek dictionary for kindle. I donwloaded it but i couldn't use it in kindle. How do you use it? I think it has only the coude source, not a mobi, epub or azw file.
How can i generate one?
Thanks.

**Comment by itayperl** [comment]
Hi,
You can get the "compiled" dictionary (lsj.prc) from the Releases page:
https://github.com/itayperl/lsj-kindle/releases

**Comment by carvalhar** [comment]
Thanks!

But i tried but it didn't work. I moved the prc file to kindle and it appears in dictionary folder (as a colletction), but it doesn't prompt when i click in greeks words, as commom dictionaries do.

it's like it's a book.

I tried by calibre to convert the prc to mobi, but it's taking a huge amont of time and it isn't advancing in the progress bar...

i'm using paperwithe. do you know what should be happening?

**Comment by itayperl** [comment]
I just transfer the prc file to the Kindle and it works fine. No conversion is needed.

Maybe the e-book you're reading is not marked as being in Greek?
See if it works with the mobi file from here: http://bencrowder.net/books/iliad/. This one worked for me. If it does, then the problem is with your e-book and not the dictionary.

**Comment by carvalhar** [comment]
Yeah, it worked like a charm =)

But why this greek dictionary doens't work with english text that contains ancient greek citations? 
For example, if you send a webpage to kindle, like this
https://en.wiktionary.org/wiki/Citations:%CF%80%CE%B5%CF%81%CE%B9%CF%83%CF%80%CE%B1%CF%83%CE%BC%CF%8C%CF%82

Usually I can see a list of dictionary, as many languages as i have, but with this greek dictionary it doesn't appear in the list. (although i could use it in the e-book marked as greek text.)

What is happening, do you know?

Thanks!

**Comment by carvalhar** [comment]
Hi, it is working now, even with webpages pushed to kindle.

i have no ideia why it didn't work before. 

But, thanks a lot for the dictionary.

**Comment by itayperl** [comment]
Cool, glad it's working for you!
